import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SocketContextProvider from "@/contexts/socket-context-provider";
import RoomContextProvider from "@/contexts/room-context-provider";
import PuzzleContextProvider from "@/contexts/puzzle-context-provider";
import Header from "@/components/header/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-page`}
      >
        <PuzzleContextProvider>
          <RoomContextProvider>
            <SocketContextProvider>
              <div className="flex flex-col h-screen">
                <Header />
                {children}
              </div>
            </SocketContextProvider>
          </RoomContextProvider>
        </PuzzleContextProvider>
      </body>
    </html>
  );
}
